set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(Boost COMPONENTS json REQUIRED)

set(ISCE_LIBRARY ${Boost_LIBRARIES})
set(ISCE_INCLUDE ${CMAKE_SOURCE_DIR};${Boost_INCLUDE_DIR})