set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(Boost COMPONENTS json REQUIRED)
find_package(PostgreSQL REQUIRED)

set(BOOST_ALL_NO_LIB 1)

set(ISCE_LIBRARY ${Boost_LIBRARIES};PostgreSQL::PostgreSQL)
set(ISCE_INCLUDE ${CMAKE_SOURCE_DIR}/isce/include;${Boost_INCLUDE_DIR};${PostgreSQL_INCLUDE_DIRS})

