set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

find_package(Boost REQUIRED)

set(ISCE_LIBRARY ${Boost_LIBRARY_DIRS})
set(ISCE_INCLUDE ${CMAKE_SOURCE_DIR};${Boost_INCLUDE_DIR})